# Generated by Django 4.0.3 on 2022-03-26 11:01

from django.db import migrations, models
import utils.image


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='media/music_cover/default.png', upload_to=utils.image.get_file_path),
        ),
    ]
