# Generated by Django 4.0.3 on 2022-03-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('language', models.CharField(choices=[('P', 'Persian'), ('E', 'English')], max_length=1)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', to='music.song')),
            ],
        ),
    ]
