# Generated by Django 4.0.3 on 2022-03-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
