# Generated by Django 4.0.3 on 2022-04-12 06:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0008_alter_subtitle_song_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Views',
            new_name='View',
        ),
    ]
