# Generated by Django 4.0.3 on 2022-04-12 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0009_rename_views_view'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('user', 'song')},
        ),
    ]
