# Generated by Django 4.0.3 on 2022-04-16 06:27

from django.db import migrations, models
import utils.image


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='media/playlist/', upload_to=utils.image.get_file_path),
        ),
    ]
