# Generated by Django 4.0.3 on 2022-04-16 09:26

from django.db import migrations, models
import utils.image


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_playlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default='music_cover/default.png', upload_to=utils.image.get_file_path),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='playlist/default.png', upload_to=utils.image.get_file_path),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.song'),
        ),
    ]
