# Generated by Django 4.0.3 on 2022-04-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_album_image_alter_playlist_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artists',
        ),
    ]
