# Generated by Django 4.0.3 on 2022-04-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_rename_artist_song_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', related_query_name='views', to='music.song'),
        ),
    ]
