# Generated by Django 4.0.3 on 2022-04-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_alter_like_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
