# Generated by Django 4.0.3 on 2022-04-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_alter_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
