# Generated by Django 4.0.3 on 2022-05-03 13:21

from django.db import migrations, models
import utils.image


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_alter_view_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default='music_cover/default.png', upload_to=utils.image.get_file_path),
        ),
        migrations.AlterField(
            model_name='view',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
