# Generated by Django 4.0.3 on 2022-05-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_alter_song_image_alter_view_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['song'], name='music_view_song_id_dfdfa2_idx'),
        ),
    ]
