# Generated by Django 4.0.3 on 2022-05-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_view_music_view_song_id_dfdfa2_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='view',
            name='music_view_song_id_dfdfa2_idx',
        ),
    ]
