version: '3.7'
services:
  realmusic:
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    env_file:
      - .env
    networks:
      - realmusic
    ports:
      - 80:80
    volumes:
      - .:/realmusic
      - media_volume:/realmusic/media/
      - static_volume:/realmusic/static/
    depends_on:
      - db
      - redis
    restart: on-failure
    image: realmusic:latest
    container_name: realmusic

  db:
    image: postgres:13.1
    networks:
      - realmusic
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=realmusic
      - POSTGRES_USER=mam3d
      - POSTGRES_PASSWORD=testing321
    restart: on-failure
    container_name: realmusic_db

  redis:
    image: redis
    networks:
      - realmusic
    restart: on-failure
    container_name: redis
  
  # nginx:
  #   build: 
  #     context: ./nginx
  #   networks:
  #     - realmusic
  #   ports:
  #     - 1300:80
  #   restart: on-failure
  #   container_name: nginx
  #   volumes:
  #     - media_volume:/realmusic/media/
  #     - static_volume:/realmusic/static/
  #   depends_on:
  #     - realmusic


networks:
  realmusic:

volumes:
  postgres_db:
  media_volume:
  static_volume:
  