# Generated by Django 4.0.3 on 2022-04-24 09:35

from django.db import migrations, models
import utils.image


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_remove_artist_slug_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='artist_iamge/default.png', upload_to=utils.image.get_file_path),
        ),
    ]
