# Generated by Django 4.0.3 on 2022-05-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
