# Generated by Django 4.0.3 on 2022-05-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_verifyemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyemail',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
