# Generated by Django 4.0.3 on 2022-05-03 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_verifyemail_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyemail',
            name='counter',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
