# Generated by Django 4.0.3 on 2022-05-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_verifyemail_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifyEmail',
        ),
    ]
